apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: aiops-analytics
  app.kubernetes.io/component: <CHANGE_ME>
  app.kubernetes.io/managed-by: aicoe-aiops-argocd

resources:
  - imagestream.yaml
  - cron-workflow.yml

generators:
  - ksops.yaml
